### ISSUE TITLE
NoUnused.Patterns: Report unused pattern declarations

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/review-unused#1]
`NoUnused.Variables` does not report pattern variables. This means that in the following example, `b` will not get reported. 

```elm
foo =
  let
    (a, b) = bar
  in
  a
```

This is on purpose because there can be value in giving `b` a name.

The improvement here, would be to report the whole pattern, when none of the pattern variables are used.

```elm
foo =
  let
    (a, b) = bar
    ^^^^^^
  in
  1
```

This is valid for other types of patterns obviously, like `{a, b}`.

**Comment by BrianHicks** [comment]
Kind of a drive by comment here, but I'm curious: what is the value in giving `b` a name?

In my perspective, it's a smell to keep around—if you do not use it, you can introduce shadowing later. If you put it in a `_ = Debug.log "b" b` then you add a use and the rule shouldn't match anyway.

I would suggest a fix of using `Tuple.first` or assigning `(a, _) = bar` to make it really clear that the second item in the tuple is not being used.

**Comment by jfmengels** [comment]
> In my perspective, it's a smell to keep around

I agree with you. Most of the time, I hide the part of the pattern that I do not use. But I think that in some (rarer) cases, there is value for giving names, even to unused variables/pattern elements.

The example I would give you is for instance when pattern matching an external complex and unfamiliar custom type like [`Elm.Syntax.Expression.Expression`](https://package.elm-lang.org/packages/stil4m/elm-syntax/7.1.0/Elm-Syntax-Expression#Expression) or [`Elm.Syntax.Declaration.Declaration`](https://package.elm-lang.org/packages/stil4m/elm-syntax/7.1.0/Elm-Syntax-Declaration#Declaration)

When I look at this [pattern match expression](https://github.com/jfmengels/elm-review/blob/1.0.0/src/Review/Rule.elm#L1288)
```elm
expressionsInDeclaration : Node Declaration -> List (Node Expression)
expressionsInDeclaration node =
    case Node.value node of
        Destructuring pattern expr ->
            [ expr ]

        -- ...
```
I find that I learn about this case when reading `pattern` "Oh ok, a destructuring expression has a pattern and an expression", even though I don't use it.

Potentially, it also prevents me from having to look at the documentation if I need to know what the first argument is. That said, I do agree that it adds to the cognitive load, and potentially the name does not match what the value is (the compiler can't help with that).

I am still very on the fence about whether to replace those names by `_` (most of the code in that section does that already), but I think that there is potential value, probably depending on the kind of person/people who is/are working on the project. Maybe they can handle large amounts of cognitive load and prefer explicitness.

Therefore I think that people should be able to choose whether to keep these names, even if they want to remove unused functions. At the moment, I think that it should be a new different rule, or maybe a configuration for this rule.

I'm curious as to what you think :)

**Comment by lydell** [comment]
I think that if there’s value in keeping an unused name, then it is kinda small. So for me it is better to sacrifice that name with an underscore so that I never have to think about it (the rule is simply “always use underscore for unused things”).

**Comment by jfmengels** [comment]
I agree with you all.
I still think it should be a different rule (which I have named `NoUnused.Patterns` in the updated title of the issue, but I'm open to a name change), because that would allow people to
- make their own choice on whether they want to enable it or not
- allow them to enable this incrementally if they had a lot of issues (different "ignore" configuration that doesn't disable the `NoUnused.Variables` rule)

**Comment by sparksp** [comment]
> I think that if there’s value in keeping an unused name, then it is kinda small. So for me it is better to sacrifice that name with an underscore so that I never have to think about it (the rule is simply “always use underscore for unused things”).

I can think of one case where you wouldn't want to swap out for an underscore, that would be unused record keys... you would just remove them from the pattern.

```elm
foo =
    let
        { a, b } = bar
    in
    a
```

Would become:

```elm
foo =
    let
        { a } = bar
    in
    a
```

And not...


```elm
foo =
    let
        { a, _ } = bar
    in
    a
```

**Comment by lydell** [comment]
True! I guess I need to amend the rule:

> Always use underscore for unused things _if it cannot be removed completely_

It would also be weird having a function with an underscore:

```elm
foo a _ b =
	...
```

Then you should lookup where `foo` is used and stop giving it the middle argument!

**Comment by sparksp** [comment]
> It would also be weird having a function with an underscore:

That actually comes up quite a lot in elm-review visitors where the functions are part of the API but you might not always care about everything being passed in. It's also used in lambda functions.

That said, I do agree that if you can remove it then you should.

**Comment by lydell** [comment]
> It's also used in lambda functions.

I try to _only_ use underscores as parameters in lambda functions. So I’d for example refactor `SomePackage.someThing foo` into `SomePackage.someThing (\a _ b -> foo a b)`.
