### ISSUE TITLE
NoUnused.CustomTypeConstructors gives false positives

### ISSUE THREAD

**Issue by jhrcek** [jfmengels/review-unused#12]
Hello @jfmengels 
I started cleaning up our codebase with elm-review 2.0.0 and it works great :+1: 
Unfortunately there are few false positives reported by the `NoUnused.CustomTypeConstructors.rule`

![Screenshot from 2020-04-20 09-48-03](https://user-images.githubusercontent.com/2716069/79727078-18e86e80-82ec-11ea-91c3-3a81a16616df.png)

What all of these cases have in common is that there are multiple modules that declare the constructor with the same name. And then one of those constructors seems to always be flagged as unused. Here's an example from IntelliJ "usages" modal:

![Screenshot from 2020-04-20 09-47-40](https://user-images.githubusercontent.com/2716069/79727243-5fd66400-82ec-11ea-82d3-158751f012f3.png)

Do you think it would it be possible to avoid such false positives?
Please let me know if you manage to reproduce this issue. Unfortunately our codebase is proprietary, so I can't share it with you, but I could try to create SSSCE for you if you don't manage to reproduce this issue.

**Comment by jfmengels** [comment]
Hello @jhrcek :wave: 

> I started cleaning up our codebase with elm-review 2.0.0 and it works great +1

Glad to hear that :blush: 

> Do you think it would it be possible to avoid such false positives?

Yes, it should be possible. I'd love an SSCCE, to make sure I don't fix it the wrong way :slightly_smiling_face:

**Comment by jhrcek** [comment]
Ok, I'ltry to come up with SSCCE and get back to you

**Comment by jhrcek** [comment]
Just to have everything in one place, here's a link to SSCCE:
https://github.com/jhrcek/elm-review-sscce/tree/FalsePositiveUnusedConstructor

**Comment by jfmengels** [comment]
This should be fixed in v2.0.1 :)

Let me know if you find anything else!

**Comment by jhrcek** [comment]
Wonderful, I confirm this kind of errors is gone :+1: Thank you
