### ISSUE TITLE
"NoUnused.Exports" seems wrong in case the export is used in a port

### ISSUE THREAD

**Issue by lucamug** [jfmengels/review-unused#25]
I get this error:

```
-- ELM-REVIEW ERROR --------------------------------- src/PayVault/Types.elm:9:7

(fix) NoUnused.Exports: Exposed type or type alias `StateFromElmToJs` is never
used outside this module.

 8|     , FormWhileEditing
 9|     , StateFromElmToJs
          ^^^^^^^^^^^^^^^^
10|     , StateFromJsToElm(..)

Errors marked with (fix) can be fixed automatically using `elm-review --fix`.
```

But the exported type is used at this line an another module:

```
port payVaultChangeStateFromElmToJs : PayVault.Types.StateFromElmToJs -> Cmd msg
```

Maybe ports are not considered?

**Comment by jfmengels** [comment]
I have created a PR in https://github.com/jfmengels/elm-review-unused/pull/40.

It would be nice if you could try it out and see it that fixes the issues you were encountering
```
elm-review --template jfmengels/elm-review-unused/preview#fix-25 --rules NoUnused.Exports
```

(PS: `jfmengels/review-unused` has been deprecated and you should now use and report issues at `jfmengels/elm-review-unused` :slightly_smiling_face: )
