### ISSUE TITLE
Read me referred to `LintConfig`

### ISSUE THREAD

**Issue by hugo** [jfmengels/review-unused#9]
In what appears to be an omission in porting this from `elm-lint` to `elm-review`, the README still refers to `LintConfig` and `Lint.Rule` as opposed to `ReviewConfig` and `Review.Rule`. I’m very unfamiliar with the Elm ecosystem, so I’m not sure if it’s possible to deploy a README fix to a package without versioning it?

(As an aside, I would like to say that the `elm-review` README section “When to write or enable a rule” is delightfully well considered and articulated.)

**Comment by jfmengels** [comment]
Hi @hugo!
Thanks for letting me know, this was indeed an unwanted omission. I have just fixed the issue :)

> I’m very unfamiliar with the Elm ecosystem, so I’m not sure if it’s possible to deploy a README fix to a package without versioning it?

It is not. I have just released a new version of the package so that people see the correct README in the packages website.

> (As an aside, I would like to say that the elm-review README section “When to write or enable a rule” is delightfully well considered and articulated.)

I'm glad to hear that, thanks :blush:
